import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider, useMutation, useQuery } from '@tanstack/react-query';
import { BrowserRouter, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import './index.css';
import './lib/i18n';
import { api } from './lib/api';

type DashboardStats = { cpuUsage: number; ramUsage: number; diskUsage: number; uptime: string; osVersion: string; hostname: string };
const queryClient = new QueryClient();
function LanguageSwitch() { const { i18n } = useTranslation(); return <button className="btn" onClick={function toggleLanguage(){ void i18n.changeLanguage(i18n.language === 'en' ? 'ru' : 'en'); }}>{i18n.language.toUpperCase()}</button>; }
function Layout({children}:{children:React.ReactNode}) { return <main className="min-h-screen p-4 md:p-8"><div className="mx-auto max-w-6xl"><header className="mb-8 flex items-center justify-between"><div><p className="text-sm text-blue-300">MegoPanel</p><h1 className="text-3xl font-bold">Server Management</h1></div><LanguageSwitch /></header>{children}</div></main>; }
function Login() { const { t } = useTranslation(); const navigate = useNavigate(); const mutation = useMutation({ mutationFn: function login(form: FormData){ return api.post('/auth/login', { username: form.get('username'), password: form.get('password') }); }, onSuccess: function onSuccess(){ navigate('/'); } }); return <Layout><form className="card mx-auto max-w-md space-y-4 p-8" action={function submit(form){ mutation.mutate(form); }}><h2 className="text-2xl font-bold">{t('login')}</h2><input className="input" name="username" placeholder={t('username')} /><input className="input" name="password" placeholder={t('password')} type="password" /><button className="btn w-full">{t('login')}</button>{mutation.error ? <p className="text-red-300">Login failed</p> : null}</form></Layout>; }
function Onboarding() { const { t } = useTranslation(); const [step,setStep] = React.useState(1); const [remote,setRemote] = React.useState(false); const adminMutation = useMutation({ mutationFn: function create(form: FormData){ return api.post('/setup/admin', { username: form.get('username'), password: form.get('password') }); }, onSuccess: function onSuccess(){ setStep(2); } }); const installMaria = useMutation({ mutationFn: function install(){ return api.post('/install/mariadb', { remoteAccess: remote }); }, onSuccess: function onSuccess(){ setStep(3); } }); const installNginx = useMutation({ mutationFn: function install(){ return api.post('/install/nginx'); }, onSuccess: function onSuccess(){ window.location.href = '/login'; } }); return <Layout><section className="card mx-auto max-w-2xl p-8"><h2 className="mb-6 text-2xl font-bold">{t('onboarding')}</h2>{step === 1 ? <form className="space-y-4" action={function submit(form){ adminMutation.mutate(form); }}><h3>{t('createAdmin')}</h3><input className="input" name="username" placeholder={t('username')} /><input className="input" name="password" type="password" placeholder={t('password')} /><input className="input" name="confirm" type="password" placeholder={t('confirm')} /><button className="btn">{t('next')}</button></form> : null}{step === 2 ? <div className="space-y-4"><h3 className="text-xl">MariaDB</h3><p>Status: {installMaria.isSuccess ? t('installed') : t('notInstalled')}</p><label className="flex gap-3"><input type="checkbox" checked={remote} onChange={function change(event){ setRemote(event.target.checked); }} />{t('remote')}</label><button className="btn" onClick={function click(){ installMaria.mutate(); }}>{t('install')}</button></div> : null}{step === 3 ? <div className="space-y-4"><h3 className="text-xl">Nginx</h3><p>Status: {installNginx.isSuccess ? t('installed') : t('notInstalled')}</p><button className="btn" onClick={function click(){ installNginx.mutate(); }}>{t('install')}</button></div> : null}</section></Layout>; }
function Dashboard() { const { t } = useTranslation(); const stats = useQuery({ queryKey: ['dashboard'], queryFn: async function load(){ const response = await api.get<DashboardStats>('/dashboard'); return response.data; } }); const cards = stats.data ? [[t('cpu'), stats.data.cpuUsage + '%'], [t('ram'), stats.data.ramUsage + '%'], [t('disk'), stats.data.diskUsage + '%'], [t('uptime'), stats.data.uptime], [t('os'), stats.data.osVersion], [t('hostname'), stats.data.hostname]] : []; return <Layout><div className="grid gap-4 md:grid-cols-3">{cards.map(function render(card){ return <article className="card p-6" key={card[0]}><p className="text-sm text-slate-400">{card[0]}</p><p className="mt-3 text-2xl font-bold">{card[1]}</p></article>; })}</div></Layout>; }
function Gate() { const setup = useQuery({ queryKey: ['setup'], queryFn: async function load(){ const response = await api.get<{configured:boolean}>('/setup/status'); return response.data; } }); const me = useQuery({ queryKey: ['me'], queryFn: async function load(){ const response = await api.get('/auth/me'); return response.data; }, retry: false, enabled: setup.data?.configured === true }); if (setup.isLoading) { return <Layout><p>Loading...</p></Layout>; } if (setup.data?.configured === false) { return <Navigate to="/onboarding" />; } if (me.isError) { return <Navigate to="/login" />; } return <Dashboard />; }
function App() { return <QueryClientProvider client={queryClient}><BrowserRouter><Routes><Route path="/" element={<Gate />} /><Route path="/login" element={<Login />} /><Route path="/onboarding" element={<Onboarding />} /></Routes></BrowserRouter></QueryClientProvider>; }
ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(<App />);
